apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgAtDBtXfi+aCyoYNrai8mCtOP7u3wbu8A1pIXKuiGj3bkTOZMrr+Bv6AV38bcb4JFoHpv5QJ3dHkMxhA2knTLgynrQu5LbIaxBrQeN+WYsfWlWNbTlaDnOprVJ9H8HEzYi8IJ+0Dv7+SRwd8g24Udm5WubMYZg6vHlDWC/73Wvw54yNJkLie/GMFupxiaA3ROjfApoUeYMmjWHBZ+LGgTS5aeT4sX2dK+9YQ+WmO8/331WluKDtjxiL2hDX6bwT+MJI9Ag210mNudEGQq/5Dbv8bP8WSm5Sl8mprYU50c6NzcZOiYaztwXa8Fq/ssdMSWogXfra17EJvjFk42gclchzb5k70oY5uWON5saoNaSZWdBH9dPJX26CDCbhS+cNkC05FTHQzG9gKzS57Z1XMmsgRgkH2PazfiguTnv85Jr5H7DOODedGk9KE5tDL09s21mYzmTxDKMjXDupqkcozgUngUXSpqst4dwk2QYwokw3DMoxDgUfzx4p8CCe1Yd5irshk7kpPuHfVCiW9zcyOabt6FTToZ9PrQCLVbCnFuJVin9p7KzKp+uxx5pE3SyNAO3Ethb95nzXozmlSFC8zL+1eUpJ1kesUpV8ZWKzVvLuAK7bNecgBPl9ovVzNNPVO4e5mOm0cJy+TNYosoh/9IFurp71Dzdy5c1icdmj/XYn7nGobKwC+GzZl7R2dfcrtDzLnKaQGb8BqSSwazw=
    username: AgCowpJZpSDKnEDgCMKOn62AjR6PNImBRKGATRnp/sNfD6mEbzNyAnjLMxFZG0z3KdMEG6o/4dMptEQuJq1m4c5koq9mmNFmSiJT6+RuGjMIgNxBpnpNVrx+zeTqMGevm9Og/hFy2i2dwKcCuRpqwn++7GKLIBE9pexu3aMJzBmo6fsc+WxQBFjD/f+wY9xbKsoxkovV1KtBgs3ezP6v+mlKG8Ib8GAqQsi5x0cl3zDqtOlyAxsFgPJkTqmowhWm2YnK8KPPUL1bNaIY3AA/6QZZjaRCAejRGje6ykzioq39FVgKY8x9hfItiuiVCgeWF0jnXM5fMmr2ogk1q6CICzFUgYPZ3UWl4V4Jjug1hrYuhFW+lFuufidN7s16cp7O6hOIPGZqU6ssjis19MKP/afbOT5V+VtmKoAs2G0RpaEtjmFL6piY4C/uKfqHsJ1ZOHOIWNaWzAS21HsQu74vR5ILcVcmE7tBkftiqH4LuiKFrgwoZY3EiuY4M2mVIeQkpfLgxP4Qg37E76JQLeNnluAQiMFsXXJ+MCpPVe3TIEMSEMFbjjkQaGfE3HGQ36mUR8TQiJ6yqN+zqLun6wP1jPQ5wr2FdRjg2hIInAz2nX+euCF1aHcugf1c3Up1wVrHPgkRNMkcGagcp1INCrtYXpGIvj5RIY8fAct09q1eNOK5D/VIsF8+h2lrhaj70fCmbhsUoYbKtFQ=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

